- src/main/js/controller/input/color-picker-test.ts
- src/main/js/controller/input/color-picker.ts
- src/main/js/controller/input/color-swatch-test.ts
- src/main/js/controller/input/color-swatch-text-test.ts
- src/main/js/controller/input/h-palette-test.ts
- src/main/js/controller/input/h-palette.ts
- src/main/js/controller/input/number-text.ts
- src/main/js/controller/input/rgb-text.ts
- src/main/js/controller/input/sv-palette-test.ts
- src/main/js/controller/input/sv-palette.ts
- src/main/js/controller/ui-util.ts
- src/main/js/converter/color-test.ts
- src/main/js/converter/color.ts
- src/main/js/formatter/color-test.ts
- src/main/js/misc/color-model.ts
- src/main/js/misc/number-util-test.ts
- src/main/js/misc/number-util.ts
- src/main/js/model/color-test.ts
- src/main/js/model/color.ts
- src/main/js/parser/color-test.ts
- src/main/js/parser/color.ts
- src/main/js/view/input/color-picker.ts
- src/main/js/view/input/h-palette.ts
- src/main/js/view/input/rgb-text.ts
- src/main/js/view/input/sv-palette.ts
- src/main/sass/components/input/_color-picker.scss
- src/main/sass/components/input/_input.scss
- src/main/sass/components/input/_rgb-text.scss
Related: #10 
- Added color mode (RGB, HSV) to keep component values in HSV
- Created a RGB text input component to prevent firing multiple change events for a single change
> Fix unwanted hue changing with color picker

- src/main/js/formatter/number-test.ts
- src/main/js/formatter/number.ts
- Formatted a code
- Added test cases
> Additional fix about #19

- src/main/js/formatter/number.ts
Hello,
Bug with Safari (iOS)
_**RangeError: toFixed() argument must be between 0 and 20.**_
I have only limit the range between 0 and 20.
Thanks
:)
> Fix error on Safari:  toFixed() argument must be between 0 and 20

- src/doc/js/route/input.ts
- src/doc/js/route/monitor.ts
- src/doc/template/input.html
- src/doc/template/monitor.html
- src/main/js/api/root-color-input-test.ts
- src/main/js/api/root-number-input-test.ts
- src/main/js/api/root-number-monitor-test.ts
- src/main/js/api/types.ts
- src/main/js/controller/binding-creators/color-input.ts
- src/main/js/controller/binding-creators/input.ts
- src/main/js/controller/binding-creators/number-monitor.ts
- src/main/js/controller/input/list.ts
- src/main/js/controller/ui-util.ts
- src/main/js/converter/color-test.ts
- src/main/js/converter/color.ts
- src/main/js/model/color-test.ts
- src/main/js/model/color.ts
- src/main/js/parser/number-color-test.ts
- src/main/js/parser/number-color.ts
- src/main/js/view/input/color-swatch.ts
- tslint.json
> Adding support for various color notations

- src/doc/js/route/misc.ts
- src/doc/template/misc.html
- src/main/js/api/folder-test.ts
- src/main/js/api/folder.ts
- src/main/js/api/root-ui-test.ts
- src/main/js/api/root.ts
- src/main/js/api/types.ts
- src/main/js/controller/folder-test.ts
- src/main/js/controller/folder.ts
- src/main/js/controller/root.ts
- src/main/js/model/list.ts
- src/main/js/model/ui-controller-list.ts
Add `index` option to insert a component at specific index.
> Add index option

- src/main/js/api/folder-test.ts
- src/main/js/api/folder.ts
- src/main/js/api/root-boolean-monitor-test.ts
- src/main/js/api/root-number-monitor-test.ts
- src/main/js/api/root-string-monitor-test.ts
- src/main/js/api/root-ui-test.ts
- src/main/js/api/root.ts
- src/main/js/api/separator.ts
- src/main/js/binding/monitor.ts
- src/main/js/misc/ticker/interval.ts
- src/main/js/misc/ticker/manual.ts
- src/main/js/misc/ticker/ticker.ts
- Used Disposable for tickers
- Made separator disposable
> More disposable

- src/main/js/api/root-monitor-test.ts
- src/main/js/controller/binding-creators/number-monitor.ts
Fix a bug that monitor binding API doesn't dispose its view correctly.
> Fix bug of disposing monitor

- src/main/js/api/button-test.ts
- src/main/js/api/button.ts
- src/main/js/api/folder-test.ts
- src/main/js/api/folder.ts
- src/main/js/api/input-binding.ts
- src/main/js/api/monitor-binding.ts
- src/main/js/api/root-input-test.ts
- src/main/js/api/root-monitor-test.ts
- src/main/js/api/root-ui-test.ts
- src/main/js/api/root.ts
> Bind handler `this` to related API

- src/doc/js/route/input.ts
- src/doc/template/input.html
- src/main/js/api/types.ts
- src/main/js/controller/binding-creators/boolean-input.ts
- src/main/js/controller/binding-creators/number-input.ts
- src/main/js/controller/binding-creators/point-2d-input.ts
- src/main/js/controller/binding-creators/string-input.ts
- src/main/js/controller/input/point-2d-pad-text.ts
- src/main/js/controller/input/point-2d-pad.ts
- src/main/js/view/input/point-2d-pad.ts
> Add `inverted` option to y-axis of Point2D pad

- src/main/js/controller/input/a-palette.ts
- src/main/js/controller/input/h-palette.ts
- src/main/js/view/input/a-palette.ts
- src/main/js/view/input/h-palette.ts
- src/main/sass/_defs.scss
- src/main/sass/components/input/_color-picker.scss
- src/main/sass/components/input/_slider.scss
Improved appearance and visibility of a color picker.
Before:
After:
> Polish color picker

- src/main/js/controller/input/a-palette.ts
- src/main/js/controller/input/color-component-texts.ts
- src/main/js/controller/input/color-picker.ts
- src/main/js/controller/input/color-swatch.ts
- src/main/js/controller/input/h-palette.ts
- src/main/js/controller/input/number-text.ts
- src/main/js/controller/input/point-2d-pad-text.ts
- src/main/js/controller/input/point-2d-pad.ts
- src/main/js/controller/input/point-2d-text.ts
- src/main/js/controller/input/slider.ts
- src/main/js/controller/input/sv-palette.ts
- src/main/js/controller/ui-util.ts
- src/main/js/misc/pointer-handler.ts
- src/main/js/view/input/a-palette.ts
- src/main/js/view/input/color-picker.ts
- src/main/js/view/input/h-palette.ts
- src/main/js/view/input/point-2d-pad.ts
- src/main/js/view/input/slider.ts
- src/main/js/view/input/sv-palette.ts
- src/main/sass/_defs.scss
- src/main/sass/components/input/_color-picker.scss
- src/main/sass/components/input/_slider.scss
> Make custom components keyboard-friendly

- src/main/js/controller/input/color-component-texts-test.ts
- src/main/js/controller/input/color-component-texts.ts
- src/main/js/controller/input/color-picker.ts
- src/main/js/controller/input/color-swatch.ts
- src/main/js/controller/input/number-text.ts
- src/main/js/converter/color-test.ts
- src/main/js/converter/color.ts
- src/main/js/misc/color-model-test.ts
- src/main/js/misc/color-model.ts
- src/main/js/model/color-test.ts
- src/main/js/model/color.ts
- src/main/js/model/model-sync.ts
- src/main/js/model/picked-color-test.ts
- src/main/js/model/picked-color.ts
- src/main/js/parser/string-color-test.ts
- src/main/js/parser/string-color.ts
- src/main/js/view/input/color-component-texts.ts
- src/main/js/view/input/color-picker.ts
- src/main/sass/_defs.scss
- src/main/sass/components/input/_color-component-texts.scss
- src/main/sass/components/input/_color-picker.scss
- src/main/sass/components/input/_list.scss
> HSL color support

- src/main/js/controller/input/color-picker.ts
- src/main/js/controller/input/color-swatch.ts
- src/main/js/controller/input/point-2d-pad-text.ts
- src/main/js/controller/input/point-2d-pad.ts
- src/main/js/misc/dom-util.ts
> Toggle picker by clicking trigger button

- src/main/js/misc/color-model.ts
- src/main/js/view/input/a-palette.ts
- src/main/js/view/input/h-palette.ts
- src/main/js/view/input/sv-palette.ts
- src/main/sass/components/input/_color-picker.scss
Optimized performance of color palettes. #99
> Optimize palettes

- src/doc/js/route/input.ts
- src/doc/template/input.html
- src/main/js/api/root-string-input-test.ts
- src/main/js/api/types.ts
- src/main/js/controller/binding-creators/color-input.ts
- src/main/js/parser/string-color-test.ts
- src/main/js/parser/string-color.ts
- Fixed patterns for parsing colors
- Added `input: 'string'` option
> Fix parsing color

- src/doc/js/route/misc.ts
- src/doc/template/misc.html
- src/main/js/misc/pointer-handler.ts
- src/main/js/model/color.ts
- src/main/js/model/input-value.ts
- src/main/js/model/point-2d.ts
- src/main/js/plugin/input-binding.ts
- src/main/js/plugin/input-bindings/color-number.ts
- src/main/js/plugin/input-bindings/color-object.ts
- src/main/js/plugin/input-bindings/color-string.ts
- src/main/js/plugin/input-bindings/point-2d.ts
- Unified computing offset of `mousedown` and `mouseup`
- Added `equals` method to internal models (`Color`, `Point2d`)
> Fix duplicated change event

- src/main/sass/components/_root.scss
This fixes the small layout issue of this preview page:
https://github.com/mrdoob/three.js/pull/21185
> Fix small layout issue caused by line-height

- lib/sass/view/_view.scss
> Fix CSS for hidden view

- lib/api/types.ts
- lib/pane/monitor-boolean-test.ts
- lib/pane/monitor-number-test.ts
- lib/pane/monitor-string-test.ts
- lib/plugin/monitor-binding.ts
- src/doc/template/monitor.html
- src/doc/ts/route/misc.ts
- src/doc/ts/route/monitor.ts
- src/doc/ts/route/quick-tour.ts
> Remove deprecated option

- README.md
- src/doc/template/partial/_global-nav.html
- src/doc/template/plugin.html
> Add document for plugin system

- lib/index.ts
- lib/misc/semver-test.ts
- lib/misc/semver.ts
- rollup.config.js
- test-module/node/index.js
> Add Tweakpane.version

- lib/plugin/common/converter/ecma/nodes-test.ts
- lib/plugin/common/converter/ecma/nodes.ts
- lib/plugin/common/converter/ecma/parser-test.ts
- lib/plugin/common/converter/ecma/parser.ts
- lib/plugin/common/converter/ecma/reader.ts
- lib/plugin/common/converter/number-test.ts
- lib/plugin/common/converter/number.ts
> Implement parsing ECMAScript number expression

- src/doc/template/_template.html
- src/doc/template/plugin.html
- src/doc/ts/bundle.ts
- src/doc/ts/route/plugin.ts
> Add demo of plugins

- lib/plugin/blade/common/controller/blade-test.ts
- lib/plugin/blade/common/controller/blade.ts
- lib/plugin/blade/common/controller/input-binding.ts
- lib/plugin/blade/common/controller/monitor-binding.ts
- lib/plugin/blade/folder/controller.ts
- lib/plugin/blade/labeled/controller.ts
- lib/plugin/blade/separator/controller.ts
- lib/plugin/common/controller/controller.ts
- lib/plugin/input-binding-test.ts
- lib/plugin/input-binding.ts
- lib/plugin/monitor-binding-test.ts
- lib/plugin/monitor-binding.ts
> Fix interface of disposing plugin

- lib/plugin/blade/common/controller/input-binding.ts
- lib/plugin/blade/common/controller/monitor-binding.ts
- lib/plugin/input-binding-test.ts
- lib/plugin/monitor-binding-test.ts
Also calls `onDispose()` of plugin view
> Fix disposing plugin (take 2)

- lib/pane/ui-test.ts
- lib/plugin/blade/folder/controller-test.ts
- lib/plugin/blade/folder/controller.ts
> Implement recursive disposing

- lib/misc/semver-test.ts
- lib/misc/semver.ts
> Add support for prerelease to Semver

- lib/pane/tweakpane-test.ts
- lib/plugin/blade/common/controller/input-binding-test.ts
- lib/plugin/common/model/value-map-test.ts
- lib/plugin/common/model/value-map.ts
- lib/plugin/input-bindings/color/controller/color-swatch-text.ts
- lib/plugin/input-bindings/color/view/color-picker.ts
- lib/plugin/input-bindings/common/controller/text-test.ts
- lib/plugin/input-bindings/common/controller/text.ts
- lib/plugin/input-bindings/common/view/text-test.ts
- lib/plugin/input-bindings/common/view/text.ts
- lib/plugin/input-bindings/number/controller/number-text.ts
- lib/plugin/input-bindings/number/controller/slider-text.ts
- lib/plugin/input-bindings/number/controller/slider.ts
- lib/plugin/input-bindings/number/plugin.ts
- lib/plugin/input-bindings/number/view/number-text.ts
- lib/plugin/input-bindings/number/view/slider-test.ts
- lib/plugin/input-bindings/number/view/slider-text.ts
- lib/plugin/input-bindings/number/view/slider.ts
- lib/plugin/input-bindings/string/plugin.ts
Make some view props mutable for preparing for #180
> Experiment with mutable views

- lib/api/folder-test.ts
- lib/pane/input-color-test.ts
- lib/pane/input-number-test.ts
- lib/pane/input-point-2d-test.ts
- lib/pane/input-point-3d-test.ts
- lib/pane/input-point-4d-test.ts
- lib/pane/input-test.ts
- lib/pane/misc-test.ts
- lib/pane/monitor-test.ts
- lib/pane/ui-test.ts
- lib/plugin/blade/common/model/blade-rack-test.ts
- lib/plugin/blade/common/model/nested-ordered-set-test.ts
- lib/plugin/common/binding/ticker/interval-test.ts
- lib/plugin/common/binding/ticker/manual-test.ts
- lib/plugin/common/model/emitter-test.ts
- lib/plugin/common/model/foldable-test.ts
- lib/plugin/common/model/value-map-test.ts
- lib/plugin/input-bindings/color/converter/color-string-test.ts
- lib/plugin/input-bindings/color/model/picked-color-test.ts
- lib/plugin/input-bindings/point-2d/converter/point-2d-test.ts
- lib/plugin/monitor-bindings/number/model/graph-cursor-test.ts
- src/doc/ts/util.ts
- test-module/node/index.js
- test-module/plugin/test/node.js
instead of `throw new Error()`
> Use `assert.fail`

- lib/api/blade-api.ts
- lib/api/blade-apis.ts
- lib/api/folder.ts
- lib/api/plugins.ts
- lib/api/root.ts
- lib/api/types.ts
- lib/index.ts
- lib/pane/tweakpane-test.ts
- lib/plugin/blade.ts
- lib/plugin/blade/button/controller/button.ts
- lib/plugin/blade/button/plugin.ts
- lib/plugin/blade/button/view/button.ts
- lib/plugin/blade/folder/plugin.ts
- lib/plugin/blade/separator/plugin.ts
- lib/plugin/common/params.ts
- lib/plugin/common/tp-error.ts
- src/doc/ts/util.ts
> Blade plugin

- lib/api/tp-event.ts
- lib/api/types.ts
- lib/index.ts
- lib/plugin/blade/button/plugin.ts
- lib/plugin/blade/folder/plugin.ts
- lib/plugin/blade/separator/plugin.ts
- lib/plugin/blade/text/api/text.ts
- lib/plugin/blade/text/plugin-test.ts
- lib/plugin/blade/text/plugin.ts
- lib/plugin/common/params.ts
- lib/plugin/input-bindings/common/controller/text.ts
- src/doc/template/catalog.html
- src/doc/ts/route/catalog.ts
Experimental implementation of input blade #180
> More blade plugin

- lib/blade/button/api/button.ts
- lib/blade/common/api/blade-apis.ts
- lib/blade/common/api/blade-container.ts
- lib/blade/common/api/blade.ts
- lib/blade/common/api/input-binding.ts
- lib/blade/common/api/monitor-binding.ts
- lib/blade/common/api/test-util.ts
- lib/blade/common/controller/blade-test.ts
- lib/blade/common/controller/blade.ts
- lib/blade/common/model/blade-rack-test.ts
- lib/blade/common/model/blade-rack.ts
- lib/blade/folder/api/folder-test.ts
- lib/blade/folder/api/folder.ts
- lib/blade/folder/controller/folder-test.ts
- lib/blade/folder/controller/folder.ts
- lib/blade/labeled/controller/labeled.ts
- lib/blade/list/api/list.ts
- lib/blade/plugin.ts
- lib/blade/separator/api/separator.ts
- lib/blade/separator/controller/separator.ts
- lib/blade/slider/api/slider.ts
- lib/blade/text/api/text.ts
> Mutable folder

- lib/blade/common/controller/value-blade.ts
- lib/blade/common/model/blade-rack-test.ts
- lib/blade/common/model/blade-rack.ts
- lib/blade/folder/api/folder-test.ts
- lib/blade/label/controller/value-label.ts
- lib/blade/list/plugin.ts
- lib/blade/rack/api/rack-test.ts
- lib/blade/rack/api/rack.ts
- lib/blade/slider/plugin.ts
- lib/blade/text/plugin.ts
- lib/common/controller/list.ts
- lib/common/controller/text.ts
- lib/common/controller/value.ts
- lib/common/number/controller/slider-text.ts
This is needed to handle input blade events
> Implement ValueBladeController

- packages/core/src/blade/button/api/button-test.ts
- packages/core/src/blade/button/api/button.ts
> Add event object to button event handler

- packages/core/lib/sass/view/_folder.scss
- packages/core/lib/sass/view/common/_folder.scss
- packages/core/src/blade/common/model/foldable.ts
- packages/core/src/blade/folder/view/folder.ts
- packages/tweakpane/src/main/sass/bundle.scss
> Improve performance of shrunk folder

- packages/core/src/common/view/pointer-handler.ts
> Improve pointer event handling

- packages/tweakpane/src/doc/template/getting-started.html
> Update document for type definitions

- packages/core/src/blade/common/model/foldable.ts
> Fix initial value of `completed`

- packages/core/lib/sass/view/_color.scss
- packages/core/package.json
- packages/core/src/blade/common/model/foldable.ts
- packages/core/src/blade/folder/controller/folder.ts
- packages/core/src/blade/folder/view/folder.ts
- packages/core/src/input-binding/color/controller/color.ts
- packages/core/src/input-binding/color/view/color.ts
- packages/core/src/input-binding/point-2d/controller/point-2d.ts
> Fix unexpected clipping with inline picker

- packages/tweakpane/src/doc/template/getting-started.html
> Improve document for TypeScript development

- packages/core/src/monitor-binding/common/view/single-log.ts
- packages/core/src/monitor-binding/number/plugin-test.ts
- packages/core/src/monitor-binding/number/plugin.ts
> Add `format` to number monitor

- packages/core/src/blade/common/api/tp-event.ts
- packages/core/src/blade/common/model/blade-rack.ts
- packages/core/src/blade/input-binding/api/input-binding.ts
- packages/core/src/blade/rack/api/rack.ts
- packages/core/src/common/binding/input.ts
- packages/core/src/common/model/bound-value.ts
- packages/core/src/common/model/primitive-value.ts
- packages/core/src/common/model/value-sync.ts
- packages/core/src/common/model/value.ts
- packages/core/src/common/number/controller/number-text.ts
- packages/core/src/common/number/controller/slider.ts
- packages/core/src/input-binding/color/controller/a-palette.ts
- packages/core/src/input-binding/color/controller/h-palette.ts
- packages/core/src/input-binding/color/controller/sv-palette.ts
- packages/core/src/input-binding/point-2d/controller/point-2d-picker.ts
> Add `last` flag for change event

- packages/tweakpane/src/doc/template/misc.html
- packages/tweakpane/src/doc/ts/route/misc.ts
- packages/tweakpane/src/doc/tsconfig.json
- packages/tweakpane/src/main/ts/blade/root/api/root.ts
> Add document for `TpChangeEvent.last`

- packages/core/src/input-binding/color/converter/color-string-test.ts
- packages/core/src/input-binding/color/converter/color-string.ts
- packages/core/src/input-binding/color/plugin-number.ts
> Add support for prefix `0x`

- packages/core/src/common/number/controller/number-text.ts
- packages/core/src/common/number/controller/slider.ts
- packages/core/src/input-binding/color/controller/a-palette.ts
- packages/core/src/input-binding/color/controller/h-palette.ts
- packages/core/src/input-binding/color/controller/sv-palette.ts
- packages/core/src/input-binding/point-2d/controller/point-2d-picker.ts
> Add support for `last` flag to key events

- packages/tweakpane/package.json
> Fix homepage

- .github/workflows/ci.yml
- packages/core/src/blade/common/api/blade-rack.ts
- packages/core/src/blade/folder/api/folder.ts
- packages/core/src/blade/rack/api/rack.ts
- packages/core/src/blade/tab/api/tab-page.ts
- packages/core/src/common/binding/target.ts
> Improve binding type

- packages/core/src/common/view/pointer-handler.ts
> Add passive flag

- packages/core/src/common/dom-util.ts
> Get global object from element

- packages/core/src/blade/common/model/foldable.ts
- packages/core/src/blade/folder/controller/folder.ts
> Fix broken layout of empty folders

- packages/core/src/blade/common/api/blade-test.ts
- packages/core/src/blade/common/api/blade.ts
> Add element field to BladeApi

- packages/core/src/common/constraint/step-test.ts
- packages/core/src/common/constraint/step.ts
- packages/core/src/input-binding/number/plugin-test.ts
- packages/core/src/input-binding/number/plugin.ts
- packages/core/src/input-binding/point-2d/plugin.ts
- packages/core/src/input-binding/point-3d/plugin.ts
- packages/core/src/input-binding/point-4d/plugin.ts
> Apply initial value to step constraint

- packages/core/src/monitor-binding/number/controller/graph-log.ts
- packages/core/src/monitor-binding/number/plugin.ts
- packages/core/src/monitor-binding/number/view/graph-log.ts
> Make min/max value changeable for graph log

- packages/core/src/input-binding/color/controller/color-picker-test.ts
- packages/core/src/input-binding/color/controller/color-picker.ts
- packages/core/src/input-binding/color/controller/color-text-test.ts
- packages/core/src/input-binding/color/controller/color-text.ts
- packages/core/src/input-binding/color/controller/color.ts
- packages/core/src/input-binding/color/converter/color-number.ts
- packages/core/src/input-binding/color/converter/color-string-test.ts
- packages/core/src/input-binding/color/converter/color-string.ts
- packages/core/src/input-binding/color/converter/writer.ts
- packages/core/src/input-binding/color/model/color-model-test.ts
- packages/core/src/input-binding/color/model/color-model.ts
- packages/core/src/input-binding/color/model/color-test.ts
- packages/core/src/input-binding/color/model/color.ts
- packages/core/src/input-binding/color/plugin-number-test.ts
- packages/core/src/input-binding/color/plugin-number.ts
- packages/core/src/input-binding/color/plugin-object-test.ts
- packages/core/src/input-binding/color/plugin-object.ts
- packages/core/src/input-binding/color/plugin-string.ts
- packages/core/src/input-binding/color/util.ts
- packages/core/src/input-binding/color/view/sv-palette.ts
- packages/core/src/misc/type-util.ts
- packages/tweakpane/src/doc/template/input-bindings.html
- packages/tweakpane/src/doc/ts/route/input-bindings.ts
> Add support for float color components

- .github/workflows/ci.yml
- packages/core/src/blade/common/model/blade-rack.ts
- packages/tweakpane/package.json
- packages/tweakpane/src/main/ts/blade/slider/api/slider-test.ts
- packages/tweakpane/src/main/ts/blade/slider/api/slider.ts
- packages/tweakpane/src/main/ts/pane/blade-test.ts
- packages/tweakpane/src/main/ts/pane/input-test.ts
- packages/tweakpane/src/main/ts/pane/monitor-test.ts
- packages/tweakpane/src/main/tsconfig.json
> Fix error type for disposing blade in its change handler

- README.md
- packages/tweakpane/scripts/doc-build-html.js
- packages/tweakpane/src/doc/template/_template.html
- packages/tweakpane/src/doc/template/blades/index.html
- packages/tweakpane/src/doc/template/catalog.html
- packages/tweakpane/src/doc/template/getting-started/index.html
- packages/tweakpane/src/doc/template/index.html
- packages/tweakpane/src/doc/template/input-bindings/index.html
- packages/tweakpane/src/doc/template/migration/index.html
- packages/tweakpane/src/doc/template/misc/index.html
- packages/tweakpane/src/doc/template/monitor-bindings/index.html
- packages/tweakpane/src/doc/template/partial/_global-header.html
- packages/tweakpane/src/doc/template/partial/_global-nav.html
- packages/tweakpane/src/doc/template/plugins/index.html
- packages/tweakpane/src/doc/template/quick-tour/index.html
- packages/tweakpane/src/doc/template/theming/index.html
- packages/tweakpane/src/doc/template/ui-components/index.html
- packages/tweakpane/src/doc/ts/bundle.ts
- packages/tweakpane/src/doc/ts/simple-router.ts
Used relative paths for the next major version
> Update document structure

- packages/core/src/common/dom-util.ts
- packages/tweakpane/src/doc/ts/route/migration.ts
> Enable canvas optimization

- packages/core/src/common/constraint/definite-range-test.ts
- packages/core/src/common/constraint/definite-range.ts
- packages/core/src/common/constraint/list-test.ts
- packages/core/src/common/constraint/list.ts
- packages/core/src/common/constraint/range.ts
- packages/core/src/common/controller/list-test.ts
- packages/core/src/common/util.ts
- packages/core/src/index.ts
- packages/core/src/input-binding/boolean/plugin.ts
- packages/core/src/input-binding/color/controller/color-picker.ts
- packages/core/src/input-binding/color/controller/color-text.ts
- packages/core/src/input-binding/number/plugin.ts
- packages/core/src/input-binding/point-2d/plugin-test.ts
- packages/core/src/input-binding/point-2d/plugin.ts
- packages/core/src/input-binding/point-3d/plugin-test.ts
- packages/core/src/input-binding/point-4d/plugin-test.ts
- packages/core/src/input-binding/string/plugin.ts
- packages/tweakpane/src/doc/template/input-bindings/index.html
- packages/tweakpane/src/main/ts/blade/list/plugin.ts
- packages/tweakpane/src/main/ts/blade/slider/plugin.ts
- packages/tweakpane/src/main/ts/pane/input-test.ts
This will make users to more easily update constraints (slider range, list options, etc.).
Ref: #390, #446
> Synchronize constraint values with options

- packages/core/src/input-binding/color/controller/h-palette.ts
- packages/core/src/input-binding/color/model/color-model-test.ts
- packages/core/src/input-binding/color/model/color-model.ts
- packages/core/src/input-binding/color/model/color-test.ts
https://user-images.githubusercontent.com/602961/212525060-75c81afe-0fee-4ea5-96c8-8c5f696e8783.mov
> Improve hue slider behavior around the maximum value

- packages/core/lib/sass/view/_color-picker.scss
- packages/core/lib/sass/view/_point-2d-picker.scss
- packages/core/lib/sass/view/_tab.scss
- packages/core/src/blade/common/controller/blade-test.ts
- packages/core/src/blade/common/controller/blade.ts
- packages/core/src/blade/common/model/blade-rack-test.ts
- packages/core/src/blade/common/model/blade-rack.ts
- packages/core/src/blade/rack/controller/rack.ts
- packages/core/src/blade/tab/controller/tab-test.ts
- packages/core/src/blade/tab/controller/tab.ts
- packages/core/src/common/compat.ts
- packages/core/src/common/model/bound-value.ts
- packages/core/src/common/model/primitive-value-test.ts
- packages/core/src/common/model/primitive-value.ts
- packages/core/src/common/model/readonly-value-test.ts
- packages/core/src/common/model/readonly-value.ts
- packages/core/src/common/model/value.ts
- packages/core/src/common/model/view-props-test.ts
- packages/core/src/common/model/view-props.ts
- packages/core/src/input-binding/color/controller/color-text.ts
- packages/core/src/input-binding/color/view/a-palette.ts
- packages/core/src/input-binding/color/view/color-text-test.ts
- packages/core/src/input-binding/color/view/color-text.ts
- packages/core/src/input-binding/color/view/h-palette.ts
- packages/core/src/input-binding/color/view/sv-palette.ts
- packages/core/src/input-binding/point-2d/view/point-2d-picker.ts
- packages/core/src/misc/type-util-test.ts
- packages/core/src/misc/type-util.ts
> Make `disabled` structure more strict

- packages/core/src/common/model/reactive.ts
- packages/core/src/common/model/view-props-test.ts
- packages/core/src/common/model/view-props.ts
This fixes a bug that initial state of ViewProps isn't applied correctly.
> Fix initial behavior of ViewProps bindings

- packages/core/lib/sass/view/_color-picker.scss
- packages/core/lib/sass/view/_point-2d.scss
- packages/core/lib/sass/view/_slider.scss
- packages/core/lib/sass/view/_text.scss
- packages/core/lib/sass/view/_tooltip.scss
- packages/core/lib/sass/view/common/_color.scss
> Use math.div

- packages/core/src/blade/common/controller/blade.ts
- packages/core/src/blade/common/model/blade-rack.ts
- packages/core/src/blade/common/model/foldable.ts
- packages/core/src/common/constraint/list-test.ts
- packages/core/src/common/constraint/list.ts
- packages/core/src/common/constraint/range-test.ts
- packages/core/src/common/constraint/range.ts
- packages/core/src/input-binding/color/converter/color-string-test.ts
- packages/core/src/input-binding/color/converter/color-string.ts
- packages/core/src/input-binding/color/plugin-number.ts
- packages/core/src/input-binding/color/util.ts
- packages/core/src/input-binding/number/plugin.ts
> Remove deprecated functionalities

- packages/core/src/blade/binding/api/binding.ts
- packages/core/src/blade/binding/api/input-binding-test.ts
- packages/core/src/blade/button/plugin-test.ts
- packages/core/src/blade/common/api/events.ts
- packages/core/src/blade/common/api/rack-test.ts
- packages/core/src/blade/common/api/rack.ts
- packages/core/src/blade/common/api/tp-event.ts
- packages/core/src/blade/folder/api/folder-test.ts
- packages/core/src/blade/folder/api/folder.ts
- packages/core/src/blade/separator/plugin-test.ts
- packages/core/src/blade/tab/api/tab-test.ts
- packages/core/src/blade/tab/api/tab.ts
- packages/core/src/plugin/pool.ts
- packages/tweakpane/src/main/ts/blade/list/api/list-test.ts
- packages/tweakpane/src/main/ts/blade/list/plugin-test.ts
- packages/tweakpane/src/main/ts/blade/slider/api/slider-test.ts
- packages/tweakpane/src/main/ts/blade/slider/plugin-test.ts
- packages/tweakpane/src/main/ts/blade/text/api/text-test.ts
- packages/tweakpane/src/main/ts/blade/text/plugin-test.ts
- packages/tweakpane/src/main/ts/pane/input-test.ts
Used `TpChangeEvent.target.key` instead of `TpChangeEvent.key`.
> Refactor input binding

- packages/core/src/blade/common/model/foldable.ts
- packages/tweakpane/src/doc/ts/route/catalog.ts
> Fix broken layout of folder in hidden container

- packages/core/src/index.ts
- packages/tweakpane/package.json
- packages/tweakpane/scripts/main-test-ts-module-pre.js
- packages/tweakpane/src/main/ts/blade/root/api/preset-test.ts
- packages/tweakpane/src/main/ts/blade/root/api/preset.ts
- packages/tweakpane/src/main/ts/blade/root/api/root-test.ts
- packages/tweakpane/src/main/ts/blade/root/api/root.ts
- packages/tweakpane/test-module/package.json
> Fix bug that importPreset() breaks bound values

- packages/tweakpane/package.json
- packages/tweakpane/src/main/ts/blade/root/api/preset.ts
- packages/tweakpane/src/main/ts/blade/root/api/root-test.ts
> Fix bug that importPreset() doesn't use binding reader

- packages/tweakpane/src/doc/sass/_base.scss
- packages/tweakpane/src/doc/template/blades/index.html
- packages/tweakpane/src/doc/ts/route/blades.ts
Added a section about casting a blade to a specific type.
Ref: #427
> Update document for blades

- packages/core/src/common/params.ts
- packages/core/src/common/point-nd/util.ts
- packages/core/src/input-binding/point-2d/plugin-test.ts
- packages/core/src/input-binding/point-2d/plugin.ts
- packages/core/src/input-binding/point-3d/plugin-test.ts
- packages/core/src/input-binding/point-3d/plugin.ts
- packages/core/src/input-binding/point-4d/plugin-test.ts
- packages/core/src/input-binding/point-4d/plugin.ts
> Rename point nD params

- packages/core/src/blade/button/api/button.ts
- packages/core/src/blade/button/plugin.ts
- packages/core/src/blade/input-binding/api/input-binding.ts
- packages/core/src/blade/label/view/label.ts
- packages/core/src/blade/monitor-binding/api/monitor-binding.ts
- packages/core/src/input-binding/plugin-test.ts
- packages/core/src/input-binding/plugin.ts
- packages/core/src/monitor-binding/plugin-test.ts
- packages/core/src/monitor-binding/plugin.ts
- packages/tweakpane/src/main/ts/blade/list/api/list.ts
- packages/tweakpane/src/main/ts/blade/list/plugin.ts
- packages/tweakpane/src/main/ts/blade/slider/api/slider.ts
- packages/tweakpane/src/main/ts/blade/slider/plugin.ts
- packages/tweakpane/src/main/ts/blade/text/api/text.ts
- packages/tweakpane/src/main/ts/blade/text/plugin.ts
> Fix bug that empty label isn't applied

- packages/core/src/common/binding/target-test.ts
- packages/core/src/common/binding/target.ts
> Fix bug in class bindability detection

- packages/core/lib/sass/view/_color.scss
> Fix hit area of inline color picker

- packages/core/src/common/controller/list-test.ts
- packages/core/src/common/controller/list.ts
- packages/core/src/common/view/list-test.ts
- packages/core/src/common/view/list.ts
- packages/tweakpane/src/main/ts/blade/list/plugin-test.ts
> Fix list for complex object

- packages/core/src/blade/common/api/rack-test.ts
- packages/core/src/blade/folder/api/folder-test.ts
- packages/core/src/blade/tab/api/tab-page-test.ts
- packages/core/src/common/tp-error.ts
- packages/core/src/plugin/plugin.ts
- packages/core/src/plugin/plugins.ts
- packages/core/src/plugin/pool.ts
- packages/tweakpane/src/doc/ts/placeholder-plugin.ts
- packages/tweakpane/src/main/ts/blade/list/plugin-test.ts
- packages/tweakpane/src/main/ts/blade/slider/plugin-test.ts
- packages/tweakpane/src/main/ts/blade/text/plugin-test.ts
- packages/tweakpane/src/main/ts/pane/pane-test.ts
- packages/tweakpane/src/main/ts/pane/pane.ts
Added missing changes for https://github.com/cocopon/tweakpane/pull/553.
> Refactor plugin CSS injection

- packages/tweakpane/src/doc/template/migration/v4/index.html
Use the draft comment instead. #556
> Fix release note URL

- packages/core/src/blade/common/api/container-blade.ts
- packages/core/src/blade/folder/api/folder-test.ts
- packages/core/src/blade/folder/api/folder.ts
- packages/core/src/blade/tab/api/tab-page.ts
- packages/core/src/blade/tab/api/tab-test.ts
> Make tab refreshable

- packages/core/lib/sass/view/_tab.scss
- packages/tweakpane/src/doc/ts/route/theming.ts
> Fix invisible tab

- packages/core/src/blade/binding/api/binding-test.ts
- packages/core/src/blade/binding/api/binding.ts
- packages/core/src/blade/button/api/button-test.ts
- packages/core/src/blade/button/api/button.ts
- packages/core/src/blade/common/api/event-listenable.ts
- packages/core/src/blade/common/api/rack-test.ts
- packages/core/src/blade/common/api/rack.ts
- packages/core/src/blade/folder/api/folder-test.ts
- packages/core/src/blade/folder/api/folder.ts
- packages/core/src/blade/tab/api/tab-test.ts
- packages/core/src/blade/tab/api/tab.ts
- packages/core/src/common/model/emitter-test.ts
- packages/core/src/common/model/emitter.ts
- packages/core/src/index.ts
- packages/tweakpane/src/main/ts/blade/list/api/list-test.ts
- packages/tweakpane/src/main/ts/blade/list/api/list.ts
- packages/tweakpane/src/main/ts/blade/slider/api/slider-test.ts
- packages/tweakpane/src/main/ts/blade/slider/api/slider.ts
- packages/tweakpane/src/main/ts/blade/text/api/text-test.ts
- packages/tweakpane/src/main/ts/blade/text/api/text.ts
> Add `off()` to unlisten events

- .gitignore
- README.md
- packages/tweakpane/package.json
More friendly guide to install additional `@tweakpane/core`.
https://github.com/cocopon/tweakpane/issues/432#issuecomment-1689139630
> Improve npm docs

- packages/tweakpane/src/doc/template/partial/_global-nav.html
Current: `https://tweakpane.github.io/docs//v3/`
Fixed: `https://tweakpane.github.io/docs/v3/`
> Remove duplicated path separator

- packages/core/src/blade/button/api/button-test.ts
- packages/core/src/blade/button/api/button.ts
- packages/core/src/blade/button/controller/button.ts
- packages/core/src/blade/common/api/tp-event.ts
> Add `native` property for mouse event

- packages/core/src/input-binding/boolean/controller/checkbox.ts
- packages/core/src/input-binding/boolean/view/checkbox.ts
> Prevent unwanted text selection

- packages/core/lib/sass/view/_checkbox.scss
- packages/core/lib/sass/view/_color-picker.scss
- packages/core/lib/sass/view/_color-swatch.scss
- packages/core/lib/sass/view/_slider.scss
- packages/core/lib/sass/view/_tab.scss
- packages/tweakpane/src/doc/sass/_pages.scss
- packages/tweakpane/src/doc/sass/components/_page-header.scss
- packages/tweakpane/src/doc/sass/components/_theme-builder.scss
This change will reduce the size of the compressed JS file from 152,325B to 152,175B (-0.0985%) ;)
> Replace bottom/left/tight/top with inset

- packages/core/src/input-binding/color/converter/color-string-test.ts
- packages/core/src/input-binding/color/converter/color-string.ts
> Fix regex pattern for parsing color
